-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 14:42:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema postgres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema postgres
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table "Juge"
-- -----------------------------------------------------
CREATE TABLE  "Juge" (
  "id" INT UNIQUE,
  "prenom" VARCHAR(45) NOT NULL,
  "nom" VARCHAR(45) NOT NULL,
  "age" INT NOT NULL,
  PRIMARY KEY ("id"));


-- -----------------------------------------------------
-- Table "Avocat"
-- -----------------------------------------------------
CREATE TABLE  "Avocat" (
  "id" INT UNIQUE,
  "prenom" VARCHAR(45) NOT NULL,
  "nom" VARCHAR(45) NOT NULL,
  "type" INT NOT NULL,
  PRIMARY KEY ("id"));


-- -----------------------------------------------------
-- Table "Partie"
-- -----------------------------------------------------
CREATE TABLE  "Partie" (
  "id" INT UNIQUE,
  "prenom" VARCHAR(45) NULL,
  "nom" VARCHAR(45) NULL,
  "Avocat_id" INT NOT NULL,
  PRIMARY KEY ("id", "Avocat_id"),
  CONSTRAINT "fk_Partie_Avocat"
    FOREIGN KEY ("Avocat_id")
    REFERENCES "Avocat" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "Proces"
-- -----------------------------------------------------
CREATE TABLE  "Proces" (
  "id" INT UNIQUE,
  "date" TIMESTAMP NOT NULL,
  "devantJury" INT NOT NULL,
  "Juge_id" INT NOT NULL,
  "PartieDefenderesse_id" INT NOT NULL,
  "PartiePoursuivant_id" INT NOT NULL,
  "decision" INT NULL,
  PRIMARY KEY ("id", "Juge_id", "PartieDefenderesse_id", "PartiePoursuivant_id"),
  CONSTRAINT "fk_Procès_Juge1"
    FOREIGN KEY ("Juge_id")
    REFERENCES "Juge" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Procès_Partie defenderesse1"
    FOREIGN KEY ("PartieDefenderesse_id")
    REFERENCES "Partie" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Procès_Partie1"
    FOREIGN KEY ("PartiePoursuivant_id")
    REFERENCES "Partie" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "Seance"
-- -----------------------------------------------------
CREATE TABLE  "Seance" (
  "id" INT UNIQUE,
  "date" TIMESTAMP NOT NULL,
  "Proces_id" INT NOT NULL,
  PRIMARY KEY ("id", "Proces_id"),
  CONSTRAINT "fk_Seance_Procès1"
    FOREIGN KEY ("Proces_id")
    REFERENCES "Proces" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "Jury"
-- -----------------------------------------------------
CREATE TABLE  "Jury" (
  "nas" INT UNIQUE,
  "prenom" VARCHAR(45) NULL,
  "nom" VARCHAR(45) NULL,
  "sexe" INT NOT NULL,
  "age" INT NOT NULL,
  "Proces_id" INT NOT NULL,
  PRIMARY KEY ("nas", "Proces_id"),
  CONSTRAINT "fk_Personne_Proces1"
    FOREIGN KEY ("Proces_id")
    REFERENCES "Proces" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE SEQUENCE  "Juge_id_sequence";
ALTER TABLE "Juge" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"Juge_id_sequence"');
CREATE SEQUENCE  "Avocat_id_sequence";
ALTER TABLE "Avocat" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"Avocat_id_sequence"');
CREATE SEQUENCE  "Partie_id_sequence";
ALTER TABLE "Partie" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"Partie_id_sequence"');
CREATE SEQUENCE  "Proces_id_sequence";
ALTER TABLE "Proces" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"Proces_id_sequence"');
CREATE SEQUENCE  "Seance_id_sequence";
ALTER TABLE "Seance" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"Seance_id_sequence"');
CREATE SEQUENCE  "Jury_nas_sequence";
ALTER TABLE "Jury" ALTER COLUMN "nas" SET DEFAULT NEXTVAL('"Jury_nas_sequence"');
